🔖 목차
1. [예외처리 종류](#1-예외처리-종류)<br/>
2. [Exception 발생시 해결방법](#2-Exception-발생시-해결방법)<br/>
3. [try~catch](#3-try-catch)<br/>
4. [throws](#4-throws)<br/>


<br/>


## 프로그램 오류 
- 프로그램 수행시 치명적 상황이 발생하여 비정상 종료 상황이 발생한 것,
- 프로그램 에러라고도 한다.

<br/>

## 오류의 종류

- 1. 컴파일 에러 : 프로그램의 실행을 막는 소스 상의 문법 에러, 소스 구문을수정하여 해결
- 2. 런타임 에러 : 입력 값이 틀렸거나, 배열의 인덱스 범위를 벗어났거나,계산식의 오류 등 주로 if문 사용으로 에러 처리
- 3. 시스템 에러 : 컴퓨터 오작동으로 인한 에러, 소스 구문으로 해결 불가

<br/>

## 오류 해결방법
- 소스 수정으로 해결 가능한 에러를 예외(Exception)라고 하는데
- 이러한 예외 상황(예측 가능한 에러) 구문을 처리 하는 방법인 예외처리를 통해 해결

<br/>

## 예외 클래스 계층구조
- Exception과 Error 클래스 모두 Object 클래스의 자손이며
- 모든 예외의 최고 조상은 Exception 클래스
- 반드시 예외 처리해야 하는 Checked Exception과 해주지 않아도 되는  Unchecked Exception으로 나뉨

![예외클래스계층구조](https://user-images.githubusercontent.com/126074577/226928201-77e9bf39-0a21-491e-bea6-e36de3ca89e6.png)

<br/>

# 1.  예외처리 종류

- 발생하는 예외에 대해서 처리하지않아도 되는 예외 를소개하겟다.

<br/>

## ArithmeticException

- 수학적으로 계산이 불가능할때 발생하는 Exception

```java
int su = 10;
int su2 = 0;
System.out.println(su/su2);
```

<br/>

## ArrayIndexOutOfBoundsException
- 배열의 인덱스 범위를 초과해서 접근할때 발생하는 예외

```java
int[] intArr = new int[5];
System.out.println(intArr[5]);
```

<br/>
 
##  ClasscastException
- 클래스형 변환을 잘못했을때발생하는 예외

```java
Object o = new String("안녕");
Integer num = (Integer)o;
```

<br/>

## NullpointException
- 참조형변수에 null값이 있을때 접근연산자를 사용하면 발생하는 Exception

```java
String name = null;
name.length();
```

<br/>


## NumberFormatException

- 문자열을 숫자형으로 변환할때 변환불가능한 문자가 있는경우

``java
int su = 10;
su=Integer.parseInt(name);
```

<br/>

## inputMissMatchException
- 입력값의 타입이 일치하지않을때 발생

```java
Scanner sc = new Scanner(System.in);
su = sc.nextInt();
//입력값  abc
```

<br/>

- **RuntimeException이 발생하면 발생하는 순간 프로그램은 종료된다.**

<br/>

# 2. Exception 발생시 해결방법

- 1.  <code>try~catch</code>문을 이용해서 직접예외를 처리하기
- 2.  <code>throws</code> 예약어를 이용해서 예외처리 위임하기

<br/>


# 3. try catch

- 먼저 예시부터 보겟다.

```java
int[] intArr = { 1, 2, 3, 4, 5 };
		try {
			int a = intArr[5];
			System.out.println(a);
			// 캐치문 괄호안에 오류내용을적어야한다.
		} catch (ArrayIndexOutOfBoundsException e) {
			// 캐치에 빠지면 이중괄호가 실행이된다.
			System.out.println("인덱스부족해!");
			int[] temp = new int[intArr.length + 5];
			System.arraycopy(intArr, 0, temp, 0, intArr.length);
			intArr = temp;
			int a = intArr[5];
		}
		System.out.println("실행되니?");
```
- 어렵게 생각하지않아도 된다.
- 우리가 많이 쓰던 if문과 비슷하다고 생각하면 쉽게느껴질것이다.
- 방법을 설명하겠다.

  - 먼저 try를 쓰고 안에 로직을 쓴다.
  - 그런후 끝나는 중괄호에 catch를 쓰고 괄호안에 오류내용을 적고 변수를 선언한다.
  - catch중괄호안에는 오류시 출력할 로직을 쓰면된다.
  - 마치 if else 같지않은가?
  - 비슷하다.

- 한가지 더 알려주자면
- 보통 오류가나면 프로그램이 종료되는데
- 오류가발생해서 catch로 빠지면 catch를 출력한후 바로 밑으로 내려가서 다음걸 읽는다.
- 이것이 **try~catch를 쓰는이유다.**

<br/>

## try문에 선언된 내용은 try문 내부에서만 사용이 가능하다.

- catch 안에도 지역변수 catch안에도 지역변수이기때문에 밖에서못쓴다.

```java
try {
	int test = 19;
	String number = "십구";
	// int result = test+Integer.parseInt(number);
} catch (NullPointerException n) {
	// System.out.println(test);
	// System.out.println(number);
	int catchNum = 100;
}
// System.out.println(test);
// System.out.println(catchNum);
```

<br/>

## try~catch문을 작성했을때 catch문을 여러개 작성할 수 있다.
- 음 if문의 elseif를 생각하면 쉽게 이해할수있을거다.
- 오류의 종류의따라 실행할 로직을 설정한다고생각하면된다.

```java
String[] names = { "유병승", null, "최하리" };
try {
	for (int i = 0; i <= names.length; i++) {
		if (names[i].length() > 2) {
			System.out.println(names[i]);
		}
	}
} catch (NullPointerException | ArrayIndexOutOfBoundsException e) {
// 예외객체의 정보를 확인할 수 있음.
	System.out.println(e.getMessage());
	// 오류메세지를 출력해준다
	// 이녀석을 가지고 어디서오류가발생했는지 알수가있다.
```

- 위에 로직안에 **getMessage()**  이런녀석이있는데 이건
- 오류메세지를 직접 출력해서 사용자가 어디에 오류가발생하는지 알수있는 메소드다.
- 오류 메세지를 알수있는 또다른메소드강 있는데
- **printStackTrace()** 이것이다.
- 예외당시 호출스택에있는 메소드정보 예외결과를 화면에출력한다.
- 두개다 오류를 출력한다는점이 같다.

<br/>

## 부모Exception 자식Exception이 발생했을때 모두 처리할수 있다.

- 말그대로 Exception 이 오류들의 부모이기때문에
- 부모를 사용해서 catch를 사용할수가있다.
- 예시를 보자

```java
Object o = new String("test");
try {
	int a = (int) o;
	a = intArr[11];
	new FileInputStream("test");
		
} catch (ClassCastException e) {
	System.out.println("형변환에러");
	// 이렇게 상속관계에잇어서 부모로 예외처리가가능하지만
	// 분기처리가안된다.
} catch (Exception e) {
	System.out.println(e.getMessage());
	System.out.println("예외처리");
}
```

- 이런식으로 부모로 예외처리를 할수있지만
- 분기처리가되지않는다
- 예를 들어서 여러개의 오류가 떳을때 모두 Exception로 예외처리를하니
- 구분할수가없다. 



<br/>

## 예외처리 구문에서 반드시 실행해야할 구문이 있는 경우

- 반드시 실행해야할 구문이 있을경우
- finally {예외가 발생하던, 안하던 무조건 실행되는 구문} 를사용한다.

```java
try {
	String n = "adbs";
	n.length();

} catch (NullPointerException e) {
	System.out.println("catch문");
	return;
} finally {
	System.out.println("반드시 실행해!");
}

```

<br/>

## 원하는 순간  Exception을 발생시키기
- <code>throw</code> 를 사용해서 발생시킬수가있다.

```java
private void exceptionTest(Object o) {
if (o instanceof String) {
	System.out.println(o);
} else {
	// 직접예외를 발생시키기
	throw new IllegalArgumentException();
	}
}
----------------------------------------------------------
exceptionTest("오호~ 내가발생시키기!");
exceptionTest(10);
```
- 이렇게 발생시킬수가 있다.
- 어떻게? throw가 위임을 시키는 기능을한다.
- 예외를 다른 곳으로 보낼수가 있다는뜻이다.
- 그러면 나중에 가면 예외처리하는곳 한곳으로 모두 모을수도 있다.

<br/>

# 4. throws

- 이녀석은 위에서 설명했듯이
- **예외를 처리했다기보다는 위임(떠넘기기)이런느낌이다.**
- 어쨋든 예외를처리를해야하기에 **위임받은곳에서 try~catch를 써야한다는거다.**

```java
public void throwsTest() throws IOException {
	FileInputStream fis = new FileInputStream("test.txt");
}
```
- 예외처리를 해야하는상황이지만
-  IOException로 위임을해서 이메소드를 예외처리한것이다.

<br/>

##  checkedException 예외가 발생하면 무조건 예외처리를 해줘야하는 Exception들....

- IOException, Exception 두가지가있다.
- IOException 자식들은 전부  checkedException이다.


```java
try {

	throw new IOException();
} catch (IOException e) {
	e.printStackTrace();

}

// 이런식으로 try~catch로 무조건 해줘야한다.

무조건해줘야하는 것들
// thrwo new FileNotFoundException();

// thrwo new EOFException();

// thrwo new SQLException();
```

<br/>

## 나만의 예외 만들기
- 
- Exception, RuntimeException,IOEception을 상속받는 클래스를 선언
- 하나의 클래스를 만든후 Exception을 상속을 받으면 그클래스는 예외처리 클래스가된다.

```java
//나만의  Exception
public class MyException extends Exception {

  public MyException(String msg) {
	super(msg);

}
------------------------------------------------
try {

	throw new MyException("나의 예외발생!!");

} catch (MyException e) {

```

- 이렇게 자기만의 예외를 만들어서 사용이가능하다.

<br/>

- 위에서는  checkedException 인걸 부모로 상속했다면
- unchecked 부모를 상속할수도 있다
- 이런경우 예외처리를 하지않아도된다.
- 예를보자

```java
//나만의 Exception
public class MyException2 extends RuntimeException {
	public MyException2(String msg) {
		super(msg);
}
-----------------------------------------------------
throw new MyException2("runtimeexception상속받은 나의exception");

	}
```
- 이런식으로 가능하다.
